README.md

Minor clean-up of mistake after merge conflict and renaming of module.

Further clean-up of Read Me

---

script/dev_docker

Fix docker script on OS X

---

README.md

- Add observing to features
- Make ToC links
- Add observe example

Minor cleanup README

---

example.py

This should make Travis happy again

Fix flake8 warnings in example.py

---

pytradfri/gateway.py
pytradfri/smart_task.py
tests/test_smart_task.py

This PR adds support for Smart Tasks, a built-in functionality to configure starting lights on certain time-intervals. Not all features are currently working as initial focus has been on the "Wake up" smart task. This class can set transition time and dimmer level for a specific device in a task, which is currently not possible in the app.
Do not merge, am working on building proper test cases.

Smart tasks

---

script/install-aiocoap.sh

Update the commit in the aiocoap installation script.
CC @lwis

Update aiocoap commit in install script

---

.coveragerc

Trying to implement coveralls to work on the test suite

Further work on coverall

---

pytradfri/device.py
pytradfri/error.py
tests/test_light.py

Coverage dropped because I've added the pytradfri directory rather than only testing the tests-folder.

Raise error instead of writing to log

---

pytradfri/device.py

Fix brightness after latest update

---

.gitignore
DockerfileRPIW
DockerfileRPIW-installed

Add Dockerfiles that work on Raspbian Stretch

---

pytradfri/const.py
pytradfri/device.py
tests/test_light.py

Lamp value ranges

---

pytradfri/device.py

Lamp value range validation

---

pytradfri/device.py
setup.py

Missing line from previous PR -- sorry!

Initialise flag for all bulbs

---

pytradfri/command.py
tests/test_command.py

Adds an extra test to take coverage of command.py to 100%
c.f. #147

Add more command tests

---

pytradfri/util.py
tests/test_util.py

Adds extra tests to take coverage of util.py to 100%
c.f. #147

Add more util tests

---

script/dev_docker

Stealing from https://github.com/home-assistant/home-assistant/blob/dev/script/dev_docker this PR will now make the comments on line 4 and 5 true.

Handle timezone as optional parameter

---

pytradfri/api/aiocoap_api.py
pytradfri/color.py
tests/api/test_aiocoap_api.py
tests/test_device.py
tests/test_util.py

Fixes a small error in _process_output.
res.code.is_sucessful is a method, not a property and as such res.code.is_sucessfull will always return true, while res.code.is_successfull() will actually check if the request is successfull or not.

Fixed _process_output not rasing error when using aiocoap_api

---

.github/workflows/test.yml
tests/__init__.py
tests/test_blinds.py
tests/test_color.py
tests/test_device.py
tests/test_group.py
tests/test_light.py
tests/test_mood.py
tests/test_socket.py

I'm still new to Github action but it doesn't look like we're actually running the test suite?

Run unit tests

---

requirements.txt
setup.py

Bump DTLSSocket to version 0.1.12, fixes #301

Bump DTLSSocket to version 0.1.12

---

docs/issue_template.md

I suggest we add a headline to the issue template to gather some extra defails about the user's local environment.

Add details to issue template

---

.devcontainer/devcontainer.json
Dockerfile
README.md

I've been playing around with VS Code and WSL on my Windows 10 machine and these settings seem to make containerized development work in its most basic form.

Add support for containerized VS code development

---

requirements_test.txt

Upgrades pre-commit to v2.14.1
Release notes: https://github.com/pre-commit/pre-commit/releases/tag/v2.14.1

Update pre-commit to 2.14.1

---

mypy.ini
pytradfri/device/__init__.py
pytradfri/device/blind.py
pytradfri/device/blind_control.py
pytradfri/device/controller.py
pytradfri/resource.py

“Raw” is sadly enough a mixture of different types, which first of all make the typing very large, and secondly not very useable, because different parts of the code depends on a subset of the typing.
Once done with typing, I think it would be good to divide raw in 3-4 different variables, simply to ensure more transparent use.

Add strict typing part 2

---

pytradfri/device/__init__.py
pytradfri/device/blind.py
pytradfri/device/blind_control.py
pytradfri/device/light.py
pytradfri/device/light_control.py
pytradfri/device/signal_repeater.py
pytradfri/device/signal_repeater_control.py
pytradfri/device/socket.py
pytradfri/device/socket_control.py
pytradfri/gateway.py

Side note from last PR.
VScode complained it did not like the relative imports, but I think I got that solved as well.

Use relative import paths for package

---

pytradfri/api/aiocoap_api.py

Both pytradfri as well as the tradfri integration in HA have for a longer time had a problem that requests stacked whenever there was a network problem.
The problem is that the async lib aiocoap do NOT raise timeout, and thus the requests hangs forever.
This PR adds a “wait_for” at the call to aiocoap, and this (re)introduces the timeout. 
The timeout is made available at async APIFactory.request() as an optional parameter “timeout=“.
Once this PR is approved and merged, a release is needed so it can be made generally avialable, a separate PR is made for the version bump.

Add timeout to async version

---

.github/workflows/test.yml
setup.py
tox.ini

- Add support for Python 3.10.
- Add trove classifiers to setup.py.

Add support for Python 3.10

---

.devcontainer/Dockerfile.dev
.devcontainer/devcontainer.json
.vscode/settings.json
script/bootstrap
script/setup

This PR improves the implementation of the VS Code dev container by switching to Python 3.10 and installing requirements in a venv.

Improve VS Code implementation

---

pytradfri/api/aiocoap_api.py

Now that I'm able to reproduce the flaky gateway error, I'm interested in learning what error code the gateway returns.

Expose error code

---

pytradfri/resource.py

Remove unused type hint constants

---

pytradfri/device/light_control.py
pytradfri/device/socket_control.py

- We changed the signature of these methods when introducing typing. I suggest we keep the boolean type for state in the signature to avoid a breaking change, and to keep the type more narrow.

Fix light and socket set_state

---

pytradfri/api/aiocoap_api.py
pytradfri/command.py

- Follow up after https://github.com/home-assistant-libs/pytradfri/pull/448.

Use command generics in aiocoap api

---

mypy.ini
pytradfri/device/__init__.py
pytradfri/device/air_purifier.py
pytradfri/device/base_controller.py
pytradfri/device/blind.py
pytradfri/device/light.py
pytradfri/device/signal_repeater.py
pytradfri/device/socket.py
pytradfri/resource.py

It looks like there was a typo in `mypy.ini` causing us to not catch this file.

Type hint base controller

---

pytradfri/api/libcoap_api.py

Fix typing error in libcoap_api

---

.pre-commit-config.yaml
pytradfri/smart_task.py

Default root_start_action to empty list

---

pyproject.toml
pytradfri/__main__.py
setup.cfg

- Remove not used settings and disables.

Clean lint settings

---

pytradfri/smart_task.py
tests/test_smart_task.py

Adds the possibility to activate or deactivate SmartTasks.

Add state control to SmartTask

---

pytradfri/api/libcoap_api.py
pytradfri/device/air_purifier_control.py
pytradfri/gateway.py
pytradfri/smart_task.py
setup.cfg
tests/test_air_purifiers.py
tests/test_blinds.py

We can quite easiliy remove these ignores so I propose we do that.

Make flake8 ignore settings less lax

---

pytradfri/api/aiocoap_api.py
pytradfri/device/__init__.py
pytradfri/device/light.py
pytradfri/gateway.py
pytradfri/group.py
pytradfri/resource.py
pytradfri/smart_task.py
tests/api/test_aiocoap_api.py

I ran `pyupgrade` on the code base to update it to use Python 3.10 syntax.

Use Python 3.10 syntax

---

.devcontainer/devcontainer.json

Settings and extensions should now reside under customizations/vscode.

Refactor devcontainer.json to use new settings format

---

pytradfri/device/__init__.py
pytradfri/device/air_purifier.py
pytradfri/device/blind.py
pytradfri/device/light.py
pytradfri/device/socket.py
pytradfri/gateway.py
pytradfri/group.py
pytradfri/resource.py
pytradfri/smart_task.py
requirements.txt

This PR allows us to bump to pydantic v2 using a minimum effort. Related to #720.

Bump pydantic to 2.10.4 from 1.10.19

---

pytradfri/device/__init__.py
pytradfri/gateway.py
pytradfri/resource.py
tests/test_device.py
tests/test_gateway.py

- https://docs.python.org/3/library/datetime.html#datetime.datetime.utcfromtimestamp

Replace deprecated datetime.utcfromtimestamp
