.travis.yml
LICENSE
opentradfri/coap_cli.py
requirements_test.txt
tests/test_device.py
tests/test_gateway.py

- The tests didn't get updated during the rename so no longer worked.
- Adds a TravisCI file to automatically run the tests + flake8
- Fix the lint issue the flake8 found.
After this PR, to enable TravisCI, [go here](https://travis-ci.org/profile)

Finish rename, prepare for automatic testing, lint.

---

pytradfri/coap_cli.py

Most linux distribution (including the dev Docker container) have /usr/local/bin configured in their PATH.
Plus removing the absolute path also allows users to have coap-client installed in a different location without having to update the source code to reflect this change.

Remove absolute path to coap-client

---

README.md
pytradfri/coap_cli.py
script/install-coap-client.sh

Prevent coap-client from outputting annoying debug output to stdout, which we need to filter out afterwards.
Using some autoconf magic ensures no modifications to the coap source code are made.
This might also be useful for #2, as coap-client now provides a clean json stream when subscribed.

Disable coap-client debug output.

---

pytradfri/coap_cli.py

I noticed that the identity (-u user) property is not needed when using the coap-client so I removed it.
In fact it seems advised to actually not use it according to [this article](https://bitsex.net/software/2017/coap-endpoints-on-ikea-tradfri/)
>   UPDATE: Leave PSK identity blank.

Removed identity since it's not needed

---

pytradfri/coap_cli.py

This is a cleaner version of @diplix' patch (#17).

Reorder coap_client arguments. Fixes #14.

---

pytradfri/coap_cli.py
pytradfri/device.py
pytradfri/group.py
pytradfri/mood.py
pytradfri/resource.py

This adds support for observing devices. I did shuffle some arguments around (related to #17 and #19). I think that the problem is related to having the arguments be after the url.
Returned API object now has a new method `observe`. Call it with a path, time to observe and a callback.
I've added support to this for devices, so that you can observe a device, which will update and then call your callback.
```python
def beer(device):
print(device.name + " is now " + str(device.light_control.lights[0].state))
lights[0].observe(beer)
```
**Update:** generalized the code so that now we can observe groups and moods too.
**Update 2:** Added `set_dimmer` and `set_state` to the group object.

Add support for observing resources.

---

Dockerfile
script/aiotry.py
script/install-aiocoap.sh

This updates our Dockerfile to allow experimentation with aiocoap. Aiocoap is a pure Python implementation based on asyncio. This would mean we no longer have to depend on calling a process to communicate with IKEA.
This branch contains support for getting the right branch of aiocoap working + the cython bindings for tinydtls. I've included a small demo script in the scripts dir for now to show that it works.
```python
script/dev_docker
[ in docker shell ]
cd script
python3 aiotry.py <IKEA KEY>
```
That will give you an output like this:
```
root@moby:/usr/src/app/script# python3 aiotry.py SECRETKEY
decrypt_verify(): found 24 bytes cleartext
decrypt_verify(): found 46 bytes cleartext
RECEIVED STATUS 2.05 Content
RECEIVED PAYLOAD [65536,65537,65538,65539,65540]
Exception ignored in: …
```

Allow aiocoap experimentation

---

pytradfri/api.py

If you wrap the func, you can't get access to `observe`. I was debating on whether or not this should have been a class?

Support for wrapping API requests

---

example_async.py
pytradfri/api/aiocoap_api.py
pytradfri/device.py

Feedback welcome, if there's a better way of handling this please let me know.
The reasons for this;
- If a new protocol is created for every request, a maximum of 3 observations can be obtained, this may be due to sockets or limitations elsewhere.
- In my testing, if a protocol is created and the Gateway is turned off, then turned on again, no further requests appear to be successful

Cache protocol for better performance, and to fix observation issues

---

README.md

Add instruction to readme to install Cython for Python 3, as this needs to be installed beforehand in order to install aiocoap using the included install script.

Update README.md with note about cython3

---

script/install-aiocoap.sh

This patch fixes the tinydtls gitlab link (it was missing the .git suffix).

Fix git URL in aiocoap.sh

---

Dockerfile

Without it it's not possible to use pytradfri API in `./script/dev_docker` when bulbs have utf-8 chars in names.

Set global UTF-8 locale

---

pytradfri/color.py
pytradfri/device.py
tests/test_color.py

This is the foundation needed for #50.
I tested the function with some values and it works great when looking at this image: https://upload.wikimedia.org/wikipedia/commons/3/3b/CIE1931xy_blank.svg
The function uses the sRGB function with D65 white, also I wanted to keep this function minimalistic.
@matemaciek's PR is the base for this, as the RGB color stuff should be integrated in color.py, I think. 
When more sophisticated conversion functions may be needed in the future, https://github.com/gtaylor/python-colormath might be worth a try.
The inverse function to calculate RGB from given xyY would also maybe be useful.

Add sRGB to xyY conversion

---

pytradfri/__main__.py
pytradfri/const.py
pytradfri/gateway.py

Might be useful to some users (see #54). 
I'm not sure about the return behaviour if the command fails. 
After a reboot is issued the enumeration for the devices in pytradfri might change. Also the GW doesn't seem to transport any commands for quite some time (5mins?).

added GW functions reboot() and factory_defaults()

---

pytradfri/__main__.py
pytradfri/api/libcoap_api.py

This is a solution proposed by @rudyvan

Resolve issue with libcoap API

---

pytradfri/device.py
setup.py
tests/test_light.py

In the current prod version of the code, Travis throws an error in device.py (#76). Oddly, the error wasn't there when the affected lines of code was first merged. This is a fix for that error so that Travis can build again. I've also added a test for the set_predefined_color-method.

Fixing device.py so that Travis doesn't fail and added test

---

LICENSE

As this is now known as pytradfri, the name in the license should be changed accordingly.

Update LICENSE from opentradfri to pytradfri

---

pytradfri/api/aiocoap_api.py

This allows us to put a request in an async_timeout for example.
(aiocoaps default timeout is 1+ minute, and it can spit out a lot of DTLS error in certain conditions)
See: https://github.com/ggravlingen/pytradfri/issues/110

cleanup on asyncio.CancelledError

---

example_pair.py
pytradfri/api/aiocoap_api.py
pytradfri/const.py
pytradfri/gateway.py

This adds support for the reverse-engineered (well, just read the network logs) commissioning process as a library call and an example program that spews nice messages to it and crudely displays newly paired devices.
A first commit fixes a race condition that happens when a program (like the example) aggressively starts accessing multiple resources on the server "simultaneously". (Not that the requests would actually overlap because they're CONs and CoAP doesn't by default allow more than one of them at a time, but still, the application can leave that scheduling to the libraries).

Support and utility for pairing (commissioning)

---

pytradfri/device.py

Added to and tested for the following methods:
- set_color_temp
- set_hex_color
- set_xy_color
- set_hsb
- set_predefined_color

Add transition_time to more methods

---

README.md
example_async.py
example_color.py
example_pair.py
example_sync.py
pytradfri/__main__.py

Psk handling clarification

---

pytradfri/api/libcoap_api.py

I believe it's a known bug (though I can't find the issue) that in sync mode the observer always stops after 90 seconds. It was thought this was a bug in Libcoap itself, but it turns out it's just a default. From `$ coap-client -h`:
```
-B seconds	break operation after waiting given seconds
(default is 90)
```
Adding the -B flag with the observation duration to the command fixes this bug. Though make sure `duration > 0` otherwise it goes haywire.

Libcoap observer timeout fix

---

pytradfri/device.py
setup.py
tests/devices.py
tests/test_device.py
tests/test_light.py

PR #141 proved to be based on incorrect assumptions so we're rolling it back.
Closes #150

Partial reversal of PR #141

---

pytradfri/api/libcoap_api.py
pytradfri/command.py
tests/api/test_libcoap_api.py

- It turns out that aiocoap doesn't have configurable request timeouts. Need changes there before aiocoap I/O API can have configurable timeouts.
Closes #154

Move timeout to I/O API

---

pytradfri/device.py
setup.py

Not sure why this was removed with the range validation, but it's needed in order to know what features a bulb supports.

Re-add supported features.

---

tests/test_device.py

Removes an unused fixture
Adds an extra test to take coverage of device.py to 100%
c.f. #147

Add extra device test

---

.coveragerc

I don't think it makes sense to include the CLI in the coverage stats as it isn't part of the library code, more like an example?

Omit main from coverage

---

pytradfri/api/aiocoap_api.py
setup.py

Catch OSError and socket.gaierror when fetching a response with aiocoap.
Can be removed when upstream issue fixed: https://github.com/chrysn/aiocoap/issues/124

Catch OSError and socket.gaierror

---

DockerfileRPI

Kept getting: ImportError: No module named 'typing'
/usr/bin/pip3 install --upgrade typing

Fixing ImportError: No module named 'typing'

---

pytradfri/api/aiocoap_api.py

> ***Comparisons can be chained arbitrarily, e.g., x < y <= z is equivalent to x < y and y <= z, except that y is evaluated only once (but in both cases z is not evaluated at all when x < y is found to be false).***
* https://docs.python.org/3/reference/expressions.html#comparisons

Simplify chained comparisons

---

README.md

tiny one-char change to make the link work again. Sorry if it's too trivial!

fix known-issues TOC link

---

script/dev_docker

When TZ is not explicitly specified, docker on mac throws up this nice error by default:
```
docker: Error response from daemon: Mounts denied:
The path /etc/localtime
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
```
Refer this upstream docker for-mac upstream issue for details: https://github.com/docker/for-mac/issues/2396
This tiny improvement makes onboarding easier for mac folks who don't want to install libcoap maybe?

[./dev_docker] fix TZ issue for docker on mac

---

pytradfri/api/aiocoap_api.py

When multiple concurrent requests fail at the same time, (for
example when the gateway is unavailable), they will try to reset
the underlying aiocoap Protocol.  This reset operation is not
async-safe and a race condition may be triggered.
This commit marks APIFactory._reset_protocol as a critical section
and introduces a lock for preventing concurrent execution.
---
<details>
<summary>AttributeError: 'NoneType' object has no attribute 'values'</summary>
```
Traceback (most recent call last):
File "/home/daan/Documents/Code/tfcd/.env/lib/python3.8/site-packages/pytradfri/api/aiocoap_api.py", line 95, in _get_response
r = await pr.response
File "/home/daan/Documents/Code/tfcd/.env/lib/python3.8/site-packages/aiocoap/protocol.py", line 816, in _run_outer
yield from cls._run(app_request, …
```

aiocoap_api: prevent race in _reset_protocol

---

README.md

fenced code blocks only really work when they are in an own paragraph, not inline.
if used inline the language selector is rendered as part of the code.

don't use fenced code block for inline code

---

.gitignore
.travis.yml
examples/debug_info.py
examples/example_async.py
examples/example_color.py
examples/example_cover_async.py
examples/example_pair.py
examples/example_socket_async.py
pytradfri/api/aiocoap_api.py
pytradfri/api/libcoap_api.py
pytradfri/command.py
requirements.txt
setup.cfg
setup.py
tests/api/test_aiocoap_api.py

This upgrades pytradfri to use aiocoap 0.4b3 and migrates credential management to the new approach.
I don't have a Tradfri gateway here so I only got as far as that aiocoap was able to find the credentials. Was not able to verify. 
Fixes #185
Can be tested using:
```
python3 examples/example_async.py <IP> -K <KEY ON BOTTOM OF GATEWAY>
```
This is a breaking change. Async API Factory now needs to be set using `await APIFActory.init(…)`

Upgrade to aiocoap 0.4b3

---

pytradfri/__main__.py
pytradfri/smart_task.py

- In my testing, the transition item is not always present in the raw dict for the SmartTaskItem instance.
- Guard the transition access by defaulting to 0 if transition is missing.

Fix smart task transition

---

pytradfri/api/aiocoap_api.py
pytradfri/command.py

- aiocoap raises a `LibraryShutdown` error when shutting down.
- Handle this error for observations and command calls.
- Make sure we stop what we're doing when getting the shut down error.
- Also handle `CredentialsMissingError` that I've seen raised when loosing connection to the gateway on shutdown.

Handle aiocoap shutdown error

---

pytradfri/__main__.py

- `set_xy_color` needs two parameters
- added set_predefined_color as an easier example

Update the examples

---

pytradfri/api/aiocoap_api.py

Avoid CredentialsMissingError after a coap request fails.
This PR is the result of https://github.com/home-assistant/core/issues/42563
This change has been tested in this context and solves the described issue.

Reload credentials when the protocol is reset

---

pytradfri/api/aiocoap_api.py

In case when  `self._psk` has not been defined yet, do not try to update credentials.

Do not update credentials when none exist

---

mypy.ini
pytradfri/api/aiocoap_api.py
requirements_test.txt
tox.ini

This is the very first step in making the interface typed, allowing a better control in integration tradfri (HA).
It solved this problem:
homeassistant/components/tradfri/link_pytradfri/api/aiocoap_api.py:31: error: Need type annotation for "_observations_err_callbacks" (hint: "_observations_err_callbacks: List[<type>] = ...")  [var-annotated]
This is tested by having a link to the library within the tradfri integration.

Add mypy and fix existing mypy errors

---

mypy.ini
pytradfri/color.py
pytradfri/command.py
pytradfri/device/controller.py

The files are not selected by random, I have made a dependency tree, and the files in this PR depend on nothing or on each other and therefore can be converted without needing to change other files.
The most important file is command.py, with a lot of changes that affect the bulk of the library as well as external use, this file need an extra careful review please.
In order to control that command.py is typed correctly, I have converted around 50% of the library and the findings flowed back into command.py. I have marked a number of code changes for a later PR, since I do not want to mix "themes".
Once this PR is corrected and merged, I will adapt the changes in the next batch and submit it. A batch is defined as:
- files that only depend on each other or already converted files
- the …

Add strict typing part 1

---

.pre-commit-config.yaml
pyproject.toml
requirements_test.txt
script/run-pre-commit.sh
setup.cfg

This PR adds but do not activate the pre-commit hooks, similar (but reduced) to HA.
It runs black/flake8/isort/mypy
to activate it run:
pre-commit install
However especially black and flake8 made a lot of corrections, so these needs to be merged first, and then githooks will be activated (saving time by not getting surprises from CI).

Add .pre-commit hooks

---

pytradfri/device/light.py

The string is currently broken 
`
[<Light #0 - name: TRADFRI bulb 2, state: on, dimmer: {self.dimmer}, hex_color: {self.hex_color}, xy_color: {self.xy_color}, hsb_xy_color: {self.hsb_xy_color}, supported features: {self.supported_features} >]
`

Fix Light representation

---

mypy.ini
tests/api/__init__.py
tests/test_device.py

- Fix incorrect tests that didn't run correctly due to incorrect logic in the tests.
- Make sure to copy constant fixture data before modifying it in tests and do it before instantiating test targets.
- Add missing test package module.
- Ignore mypy errors for tests.

Clean and fix tests

---

script/install-coap-client.sh

Hi there,
If run via "/bin/sh" (instead of "/bin/bash") the first if-expression of that script will always fail with...
```
./install-coap-client.sh: 3: [: Illegal number: 
```
... because you're comparing a string with an integer.
`$(id -u)` should be used instead.
Thanks.

fix if-expression for user-id check

---

pytradfri/api/aiocoap_api.py
pytradfri/api/libcoap_api.py
pytradfri/command.py
pytradfri/resource.py

- The type annotation for the observation error callback was incorrect. Fix that.
- I needed to fix and some additional things around the observation method in the APIs to correct typing after the error callback fix.

Fix observation err_callback typing

---

pytradfri/device/blind.py

This PR implements a `TypedDict` for the `Blind` class.

Add type annotation for Blind class

---

pytradfri/device/__init__.py
pytradfri/device/air_purifier.py
pytradfri/device/blind.py
pytradfri/resource.py
pytradfri/typing.py

Add type `TypedDict` for `ApiResource`, which combines previously added TypedDicts.
Following this PR, we will refactor and start using `pydantic`.

Type hints for ApiResource

---

mypy.ini
requirements.txt
setup.py

This PR adds `pydantic` to the list of requirements so what we can add type hints using the [library](https://pydantic-docs.helpmanual.io/).
Also adding suggested plugin settings for `mypy`:
https://pydantic-docs.helpmanual.io/mypy_plugin/#enabling-the-plugin

Add pydantic to requirements

---

mypy.ini
pytradfri/api/aiocoap_api.py
pytradfri/command.py

- See https://github.com/home-assistant-libs/pytradfri/pull/388 for the previous attempt.
- I've corrected the type for the `Command.result` as that depends on the return value of the `process_result` callback.
- I'm planning to continue working on the command typing to make it more useful in follow up PRs.

Type aiocoap api

---

pytradfri/gateway.py
tests/test_gateway.py

This PR:
- Implements pydantic for the `GatewayInfo` response
We can't add the file to the strict typing list yet as we need to add type hints for `group.py` and `mood.py` first.

Add type hints for GatewayInfo

---

pytradfri/api/aiocoap_api.py
pytradfri/api/libcoap_api.py
pytradfri/command.py
pytradfri/device/air_purifier_control.py
pytradfri/device/blind_control.py
pytradfri/device/light_control.py
pytradfri/device/socket_control.py
pytradfri/gateway.py
pytradfri/resource.py
tests/test_command.py

By making the `Command` class a generic type we can increase the information of the api method signatures and command return types.
Note that this is technically a breaking change as I've removed the setter functionality of the `Command.result` attribute. It was making the typing confusing in the api modules, so I wanted to remove this and use a regular method call instead to process the result. In practice this should not be a breaking change since it's normally only the internal api methods that process command results.
I'll follow up with more changes in the api module to take advantage of the generic command type.

Make Command generic

---

pytradfri/device/__init__.py
pytradfri/device/light.py
pytradfri/gateway.py
pytradfri/group.py
pytradfri/mood.py
pytradfri/resource.py
pytradfri/smart_task.py
tests/test_device.py
tests/test_group.py
tests/test_smart_task.py

- We only use the `Command.path` property to construct the `Command.url` and there we copy all items to string. But I think it's more consistent if we make sure that the `path` items are strings from the beginning.
fixes #449

Fix some typing issues

---

pytradfri/device/__init__.py

Fixes:
```
pytradfri/device/__init__.py:29: error: Module "pytradfri.device.air_purifier_control" does not explicitly export attribute "AirPurifierResponse"; implicit reexport disabled  [attr-defined]
pytradfri/device/__init__.py:30: error: Module "pytradfri.device.blind_control" does not explicitly export attribute "BlindResponse"; implicit reexport disabled  [attr-defined]
```

Minor type hint fixes

---

.pre-commit-config.yaml

I accidentally committed and pushed the version bump to master (have reverted that). Don't want to do the same mistake again so I'm adding a rule to pre-commit.
On a side note, I use Azure's git repos for work and we can set a rule preventing commits without PRs. Can that be on Github too? I'm not an admin of this repo so I can't check.

Add checks to pre-commit

---

pytradfri/device/air_purifier.py
tests/test_air_purifiers.py

Six months have passed since I installed the filter on the device and the `filter_lifetime_remaining` property now reports a negative value of 31 minutes. In the app, there is an indicator that the filter expires today.
I therefore propose this clarification to the `filter_status` property.
```
DeviceResponse(
id=65554,
name='Luftrenare',
created_at=1634661517,
ota_update_state=0,
air_purifier_control=[
AirPurifierResponse(
id=0,
air_quality=11,
controls_locked=0,
fan_speed=10,
filter_lifetime_remaining=-31,
filter_lifetime_total=259200,
filter_runtime=259231,
filter_status=1,
leds_off=0,
mode=1,
motor_runtime_total=259231
)
],
application_type=10,
blind_control=None,
device_info=DeviceInfoResponse(manufacturer='IKEA of Sweden', model_number='STARKVIND Air purifier', …
```

Clarify meaning of filter_status property

---

.pre-commit-config.yaml

Dependencies in the pre-commit hook configuration file were not aligned with dependencies in `requirements_test.txt`. This PR fixes that.

Bump dependencies in pre-commit hooks

---

.github/workflows/pre-commit-update.yml

I had a look to see if dependabot could keep the pre-commit hooks update. Apparently it wasn't in their roadmap, but I found this instead:
https://browniebroke.com/blog/gh-action-pre-commit-autoupdate/

Track updates of pre-commit hooks

---

.pre-commit-config.yaml

I was planning on creating a workflow using Renovate but it seemed that required creating an app, which seemed a cumbersome way to go.
Noticed we were using a mirror in the pre-commit config so I figured we could try switching to the official repo to see if that, alhtough it wouldn't make sense, helps in the incorrect version update.

Change repo to Github from Gitlab for pre-commit flake8

---

.pre-commit-config.yaml

- This simplifies the requirements version matching by using the locally installed versions.
- https://github.com/home-assistant-libs/pytradfri/pull/506#issuecomment-1160156840

Move pre-commit flake8 to local repo

---

pytradfri/api/aiocoap_api.py

- A protocol is needed to allow users of the library to type the `APIFactory.request` method which is the main api function in use.

Add APIRequestProtocol for APIfactory.request

---

examples/example_color.py
pytradfri/color.py
pytradfri/device/light.py
pytradfri/device/light_control.py
tests/test_light.py

- The "can_set_*" attributes on the light control instance were broken after the big refactor with Pydantic.
- Fix that by introducing a new set of properties on the Light class that returns the available features of the light.
- I think these properties belong on the Light class instead of LightControl as the LightResponse data is needed to check supported features and that data is available directly on the Light instance but only indirectly on the LigthControl instance. It doesn't matter for the LightControl instance what kind of lights it controls.

Rework light supported features

---

.coveragerc
pytradfri/device/light_control.py
tests/test_light.py

- Some light bulbs support receiving multiple light data items in the same command, eg dimmer and hsb color or dimmer and color temp.
- Add back a way for the library user to combine light control commands into one command with merged data.
- We removed the general way to merge commands previously as it is complicated to support the general case. There's also no known real use case for combining other commands than light control commands.
- We still have the attribute `LightControl.can_combine_commands` so it makes sense to have a method `LightControl.combine_commands`.

Add combine commands to light control

---

.github/workflows/pre-commit-update.yml
.github/workflows/test.yml
mypy.ini
pyproject.toml
setup.py
tox.ini

- I suggest we drop support for Python 3.8.
- Home Assistant only supports Python 3.9 and Python 3.10.
- aiocoap is thinking about dropping Python 3.8.
- It simplifies typing somewhat (will address in separate PR that solves pylint issues).

Remove support for Python 3.8

---

pyproject.toml
pytradfri/__main__.py
pytradfri/api/aiocoap_api.py
pytradfri/api/libcoap_api.py
pytradfri/color.py
pytradfri/device/__init__.py
pytradfri/device/base_controller.py
pytradfri/device/light_control.py
pytradfri/group.py
pytradfri/resource.py
pytradfri/smart_task.py
pytradfri/util.py
requirements_test.txt
tox.ini

- This solves the pylint issues in the pytradfri package.
- I'll follow up with more PRs for solving pylint for examples and tests.

Address remaining pylint issues in pytradfri

---

.pre-commit-config.yaml
tox.ini

With the recent additions of type hints, I believe we can enable mypy and pylint for all relevant folders. I've also merged all local hooks into one list-item.

Cleanup pre-commit config

---

setup.py

This is a follow-up to https://github.com/home-assistant-libs/pytradfri/pull/539#issuecomment-1229242499.

Bump aiocoap to 0.4.4 in setup.EXTRAS_REQUIRE

---

pytradfri/smart_task.py
tests/test_smart_task.py

Resolves #610
Also fleshed out some examples for how to interact with `SmartTask`s, happy to revert some or all of those if undesired.
Thanks for this library!

Fix smart task start action response dimmer attribute

---

.github/workflows/test.yml
setup.py
tox.ini

I read that support for Python 3.9 has been dropped in core so I guess we could drop it here too. Before doing that, I propose we add 3.11 to the pipeline run.

Add Python 3.11 to CI/CD pipeline

---

pyproject.toml

Pylint flooded output with `pylint: Command line or configuration file:1: UserWarning: Specifying exception names in the overgeneral-exceptions option without module name is deprecated and support for it will be removed in pylint 3.0. Use fully qualified name (maybe 'builtins.Exception' ?) instead.` before making this adjustment.

Fix overgeneral-exceptions error

---

pyproject.toml
requirements_test.txt
tests/api/test_aiocoap_api.py

- Use pytest-asyncio instead of custom code to test asyncio code.
- Clean up the aiocoap api tests.
- Solves this warning in CI:
```
=============================== warnings summary ===============================
tests/api/test_aiocoap_api.py::test_request_returns_single
/home/runner/work/pytradfri/pytradfri/tests/api/test_aiocoap_api.py:16: DeprecationWarning: There is no current event loop
loop = asyncio.get_event_loop()
```

Use pytest-asyncio

---

pyproject.toml

Enabling a few more of the ruff rules I found in the `core` repo's `pyproject.toml`.

Add more ruff rules

---

examples/debug_info.py
examples/example_air_purifier_async.py
examples/example_async.py
examples/example_cover_async.py
examples/example_socket_async.py
examples/example_sync.py
pyproject.toml
pytradfri/__main__.py
pytradfri/api/aiocoap_api.py
pytradfri/api/libcoap_api.py
pytradfri/device/air_purifier.py
pytradfri/gateway.py
pytradfri/group.py
pytradfri/resource.py
pytradfri/smart_task.py

The ignores in the examples files are related to these errors. Guess it's the same reason mentioned [here](https://github.com/home-assistant-libs/pytradfri/pull/651#discussion_r1125706884)?
```
(.venv) vscode ➜ /workspaces/pytradfri (ruff-d-rule) $ pylint pytradfri examples tests
************* Module pytradfri.__main__
pytradfri/__main__.py:80:33: E1133: Non-iterable value devices is used in an iterating context (not-an-iterable)
pytradfri/__main__.py:89:30: E1136: Value 'groups' is unsubscriptable (unsubscriptable-object)
pytradfri/__main__.py:90:21: E1133: Non-iterable value groups is used in an iterating context (not-an-iterable)
pytradfri/__main__.py:105:24: E1133: Non-iterable value endpoints is used in an iterating context (not-an-iterable)
pytradfri/__main__.py:117:31: E1133: …
```

Add D-rule in ruff

---

Dockerfile

`stretch` does not exist anymore in the official Python docker repo, so bullseye is used instead.
Also, switching to 3.11, as that is fully supported by this library.

Replace 3.10-stretch with 3.11-bullseye

---

pytradfri/api/aiocoap_api.py
tests/api/test_aiocoap_api.py

- If the protocol context is shutting down we're not allowed to make new requests with the context.
- Add a check if we're shutting down the protocol context when getting the context.
- This should fix reqeusts that are made after the protocol context has begun to shutdown but before the protocol context has completed the reset.
- Example stacktrace (first one):
https://github.com/home-assistant/core/issues/105004#issuecomment-1855475069
- Requests that are already in flight before the protocol context begins the shutdown are up to aiocoap to handle and flush.

Fix request while protocol context is shutting down

---

pytradfri/api/aiocoap_api.py
tests/api/test_aiocoap_api.py

- If there's an error during protocol context shutdown we want to make sure the protocol context completes the reset, so that a new protocol context is created the next time the protocol context is needed.
- Example stacktrace (second one): https://github.com/home-assistant/core/issues/105004#issuecomment-1855475069
Needs https://github.com/home-assistant-libs/pytradfri/pull/814

Fix reset protocol on error during context shutdown

---

README.md

I've seen a few posts in Swedish media that the Trådfri gateway has been deprecated by IKEA. I'm unable to find the source of the information on IKEA's web site, but one of the Swedish media outlets pointed towards this:
https://homekits.de/neue-ikea-produkte-nur-noch-mit-dirigera-hub-kompatibel/

Add information on the gateway being deprecated by IKEA

---

examples/example_pair.py
pytradfri/gateway.py
pytradfri/group.py
tests/test_gateway.py

- The type of the different id parameters should always be an integer according to the data returned by the gateway. We had mistyped this parameter in some places as a string.
- Note that this is a breaking change as we change the type of some parameters in the Gateway methods.

Fix id typing

---

pyproject.toml
pytradfri/api/aiocoap_api.py
pytradfri/smart_task.py
tests/api/test_aiocoap_api.py
tests/api/test_libcoap_api.py
tests/test_color.py
tests/test_command.py
tests/test_device.py
tests/test_gateway.py
tests/test_light.py
tests/test_mood.py
tests/test_signal_repeater.py
tests/test_smart_task.py
tests/test_socket.py
tests/test_util.py

- Add missing type annotations found by the ANN ruff linter setting group.
- https://docs.astral.sh/ruff/rules/#flake8-annotations-ann

Add missing type annotations
